version: 2.1

jobs:
  playwright-tests:
    docker:
      - image: cimg/node:lts
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci
          no_output_timeout: 20m

      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps
          no_output_timeout: 20m

      - run:
          name: Run Playwright tests
          command: npx playwright test
          no_output_timeout: 60m

      - store_artifacts:
          path: playwright-report
          destination: playwright-report

workflows:
  version: 2
  playwright-workflow:
    jobs:
      - playwright-tests
